### PR TITLE
Fix error: characters can not be displayed normally in chinese

### PR DESCRIPTION
**Pull request by wjunLu**
Some Chinese characters require more than two or three tokens to decode, tokens will be decoded immediately, rather than wait for two or three tokens.

Current output:
image

Fixed output:
image

### CODE REVIEW

**Comment by Jack-Khuu** [comment]
Thanks for the fix @wjunLu, just kicked off the CI

**Comment by Jack-Khuu** [comment]
@wjunLu PR lgtm, can you take a look at setting up your CLA? (Allows you to contribute to Facebook/Meta repos)

**Comment by wjunLu** [comment]
> @wjunLu PR lgtm, can you take a look at setting up your CLA? (Allows you to contribute to Facebook/Meta repos)

I have signed CLA, how to re-check CLA?

**Comment by Jack-Khuu** [comment]
Just kicked off the CLI again, once its good I'll merge

Thanks again!

**Review by Jack-Khuu — APPROVED** [review]

**Pull request merged**
