### PR TITLE
[Distributed] Support index + multi-bin loading

### PR DESCRIPTION
**Pull request by kwen2501**
Some HF format uses index + multiple binaries instead of index + multiple safetensors.
Distributed workflows already support the later, this PR adds support for the former too. 
(The reason is that quantized checkpoint cannot save as safetensor format yet.)

### CODE REVIEW

**Comment by mikekg** [comment]
Can you figure out from what's in the location whether it's one or the other format rather than adding another option?  (If push comes to shove, you could expect the checkpoint path point to the index file?)

**Comment by mikekg** [comment]
Does this compose with #1255  ?

**Comment by kwen2501** [comment]
> Does this compose with #1255 ?

Thanks for the review. I hope yes. 
Distributed already have support for "index + multi-safetensor" format (thanks to @lessw2020 ). 
This PR only **adds** support for "index + multi-bin" format. (The reason is that quantized checkpoint cannot save as safetensor format yet.)

**Comment by mikekg** [comment]
> > Does this compose with #1255 ?
> 
> Thanks for the review. I hope yes. Distributed already have support for "index + multi-safetensor" format (thanks to @lessw2020 ). This PR only **adds** support for "index + multi-bin" format. (The reason is that quantized checkpoint cannot save as safetensor format yet.)

How much of this can be shared with local-only weight loading?  Should distributed weight loading just be a general case of local loading (or vice versa, local just a special case of distributed?)  Not suggesting to abandon this PR at all, but similar to what you've done to merging model.py and model_dist.py (yay! Awesome work!!!!) could be a real value here.

**Review by lessw2020 — APPROVED** [review]
lgtm!
Thanks for adding this!

**Pull request merged**
