### PR TITLE
Remove last references to use_distributed argument

### PR DESCRIPTION
**Pull request by mreso**
This PR removes the last references to the use_distributed argument which got replaced by --distributed

### CODE REVIEW

**Review by lessw2020 — APPROVED** [review]
Looks good. Thanks for cleaning this up!

**Comment by lessw2020** [comment]
Test failure seems unrelated: 
`Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
  Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory`

**Comment by mreso** [comment]
> Test failure seems unrelated: `Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory Could not load library libnvrtc.so. Error: libnvrtc.so: cannot open shared object file: No such file or directory`

Yes, current main is also failing

**Review by kwen2501 — APPROVED** [review]
LGTM

**Comment by mreso** [comment]
@Jack-Khuu any thoughts on the test failure as its not PR related? Or can you by-pass it to merge? I think @byjlw did that for #1354 which failed with the same error but was merged.

**Comment by Jack-Khuu** [comment]
I'll take a look this weekend, seems like there's an upstream GH CI bug. PR lgtm though

**Review by Jack-Khuu — APPROVED** [review]

**Pull request merged**
