### PR TITLE
[AOTI] Remove the original model weights in Python deployment

### PR DESCRIPTION
**Pull request by desertfire**
Summary: Fixes https://github.com/pytorch/torchchat/issues/1302. Because AOTI-compiled model contains a copy of model weights, if we also keep the eager model weights, it will be a wast of GPU memory and even triggers OOMs. This PR releases the corresponding eager model weights in the AOTI-Python deployment path.

### CODE REVIEW

**Comment by desertfire** [comment]
@Jack-Khuu , is there any known problems with CI? Many of the failures here seem unrelated to my change.

**Comment by Jack-Khuu** [comment]
Yeah, we're checking with the DevInfra folk

**Comment by Jack-Khuu** [comment]
Heads up CI is broken in pt/pt and at higher level

https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.17.0

**Comment by byjlw** [comment]
@desertfire it should be fixed now. We just need to churn through the tests

**Comment by mikekgfb** [comment]
> Summary: Fixes #1302. Because AOTI-compiled model contains a copy of model weights, if we also keep the eager model weights, it will be a waste of GPU memory and even triggers OOMs. This PR releases the corresponding eager model weights in the AOTI-Python deployment path.

In the long term we might ask whether there's a point in going to all the expense of building the model if we just need the config.  The model build process had a config_only bool argument with the intent of allowing suppression of actual model build (that was never implemented though).  

This is particularly noteworthy (aka expensive because GGUF requires much more than weight mmaps) when building a model from GGUF, as @metascroy pointed out a long time ago when he implemented the GGUF reader.

**Review by Jack-Khuu — APPROVED** [review]

**Pull request merged**
