### PR TITLE
Remove tokens per sec in aggregate_metrics when jit_compile

### PR DESCRIPTION
**Pull request by yanbing-j**
This PR is to remove tokens per sec in aggregate_metrics when jit_compile, to make the average of tokens per sec more precise. The tokens per sec is too low when jit_compile, which should not be included in aggregate_metrics.

### CODE REVIEW

**Comment by yanbing-j** [comment]
Hi @Jack-Khuu, could you please take a look? Thanks!

**Comment by Jack-Khuu** [comment]
Thanks for adding. Looks like the compile numbers got added back in (outside of the if) with https://github.com/pytorch/torchchat/commit/77774d2345dee150d7bdc2dbd22529cbde388ed7 due to Nan's

I rebased your PR since https://github.com/pytorch/torchchat/commit/d7b681a0b8745874d11db2246a7eefbf23b07a5a added a Nan check that might actually make the old Nan problem a non-issue

**Comment by yanbing-j** [comment]
> the averages were calculated with the compile sample excluded

Updated. Please take a look again.

**Comment by Jack-Khuu** [comment]
Thanks for the comment

Just one last nit: Let's only print the "excluding compile in calculations" message if the user is actually compiling

Once that's ready give me a ping and I'll merge this in

**Comment by yanbing-j** [comment]
@Jack-Khuu Thanks for the merging!

**Pull request merged**
