### PR TITLE
bump pytorch nightly version

### PR DESCRIPTION
**Pull request by swolchok**

### CODE REVIEW

**Comment by swolchok** [comment]
looks like we need to wait until there's a torchvision nightly newer than 1108, and also there's an AOTI segfault

**Comment by Jack-Khuu** [comment]
This might play a part to the aoti bug: https://github.com/pytorch/torchchat/issues/1356

**Comment by swolchok** [comment]
> wait until there's a torchvision nightly newer than 1108

hmm, there are several days of newer nightlies. trying again to see if those errors go away.

**Comment by Jack-Khuu** [comment]
closing stale in favor of https://github.com/pytorch/torchchat/pull/1367

**Pull request closed without merging**
